# Generated by Django 5.2.11 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_preview',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
