# Generated by Django 5.2.11 on 2026-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_signature_user_username_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animerole',
            field=models.CharField(default='npc', max_length=20),
        ),
    ]
